-- Starter exercise library — run this after schema.sql.
-- Built-ins: is_custom = false, created_by = null, so RLS makes them
-- readable by every user but not editable by anyone from the app.

insert into exercises (name, muscle_group, equipment, is_custom) values
  ('Barbell Bench Press', 'Chest', 'Barbell', false),
  ('Incline Barbell Bench Press', 'Chest', 'Barbell', false),
  ('Dumbbell Bench Press', 'Chest', 'Dumbbell', false),
  ('Dumbbell Flyes', 'Chest', 'Dumbbell', false),
  ('Push-Up', 'Chest', 'Bodyweight', false),
  ('Cable Fly', 'Chest', 'Cable', false),
  ('Overhead Press', 'Shoulders', 'Barbell', false),
  ('Dumbbell Shoulder Press', 'Shoulders', 'Dumbbell', false),
  ('Lateral Raise', 'Shoulders', 'Dumbbell', false),
  ('Front Raise', 'Shoulders', 'Dumbbell', false),
  ('Face Pull', 'Shoulders', 'Cable', false),
  ('Rear Delt Fly', 'Shoulders', 'Dumbbell', false),
  ('Deadlift', 'Back', 'Barbell', false),
  ('Barbell Row', 'Back', 'Barbell', false),
  ('Pull-Up', 'Back', 'Bodyweight', false),
  ('Lat Pulldown', 'Back', 'Cable', false),
  ('Seated Cable Row', 'Back', 'Cable', false),
  ('Single-Arm Dumbbell Row', 'Back', 'Dumbbell', false),
  ('T-Bar Row', 'Back', 'Barbell', false),
  ('Back Extension', 'Back', 'Bodyweight', false),
  ('Barbell Squat', 'Legs', 'Barbell', false),
  ('Front Squat', 'Legs', 'Barbell', false),
  ('Leg Press', 'Legs', 'Machine', false),
  ('Romanian Deadlift', 'Legs', 'Barbell', false),
  ('Leg Extension', 'Legs', 'Machine', false),
  ('Leg Curl', 'Legs', 'Machine', false),
  ('Walking Lunge', 'Legs', 'Dumbbell', false),
  ('Bulgarian Split Squat', 'Legs', 'Dumbbell', false),
  ('Standing Calf Raise', 'Legs', 'Machine', false),
  ('Hip Thrust', 'Glutes', 'Barbell', false),
  ('Barbell Curl', 'Arms', 'Barbell', false),
  ('Dumbbell Curl', 'Arms', 'Dumbbell', false),
  ('Hammer Curl', 'Arms', 'Dumbbell', false),
  ('Tricep Pushdown', 'Arms', 'Cable', false),
  ('Skull Crusher', 'Arms', 'Barbell', false),
  ('Close-Grip Bench Press', 'Arms', 'Barbell', false),
  ('Dip', 'Arms', 'Bodyweight', false),
  ('Plank', 'Core', 'Bodyweight', false),
  ('Hanging Leg Raise', 'Core', 'Bodyweight', false),
  ('Cable Crunch', 'Core', 'Cable', false),
  ('Russian Twist', 'Core', 'Bodyweight', false),
  ('Treadmill Run', 'Cardio', 'Machine', false),
  ('Rowing Machine', 'Cardio', 'Machine', false),
  ('Stationary Bike', 'Cardio', 'Machine', false)
on conflict do nothing;
